# Generated by Django 2.2.14 on 2020-07-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead2',
            field=models.CharField(default=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(default=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateField(),
        ),
    ]
